INSERT INTO animations (id,`name`,`description`,`dateStart`,`dateEnd`,pictureUrl,popularity,totalPlaces,remainingPlaces,recurrence,enabled) VALUES (1,'Soirée dansante année 90','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc sed ligula pellentesque, imperdiet magna vel, bibendum diam. Nullam quis laoreet leo. Curabitur et ex non massa efficitur venenatis. Vestibulum at mi erat. Ut varius, augue vitae iaculis vehicula, sapien diam tempor mauris, in interdum libero leo ac ex. Fusce mi dui, efficitur in lectus in, tincidunt lobortis lorem. Morbi tincidunt dolor quis auctor imperdiet. Praesent nec odio lacinia, volutpat ex sed, molestie quam. Maecenas porttitor, tortor non aliquam pellentesque, dolor diam maximus neque, vitae sollicitudin orci quam venenatis risus.','2023-04-29 21:00:00','2023-04-30 1:00:00','./assets/pictures/animations/soiree-dansante-annee-90.png',1,50,29,'occasional','true');
INSERT INTO animations (id,`name`,`description`,`dateStart`,`dateEnd`,pictureUrl,popularity,totalPlaces,remainingPlaces,recurrence,enabled) VALUES (2,'Soirée détente','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc sed ligula pellentesque, imperdiet magna vel, bibendum diam. Nullam quis laoreet leo. Curabitur et ex non massa efficitur venenatis. Vestibulum at mi erat. Ut varius, augue vitae iaculis vehicula, sapien diam tempor mauris, in interdum libero leo ac ex. Fusce mi dui, efficitur in lectus in, tincidunt lobortis lorem. Morbi tincidunt dolor quis auctor imperdiet. Praesent nec odio lacinia, volutpat ex sed, molestie quam. Maecenas porttitor, tortor non aliquam pellentesque, dolor diam maximus neque, vitae sollicitudin orci quam venenatis risus.','2023-04-30 21:00:00','2023-04-30 23:00:00','./assets/pictures/animations/eclairage-ville-nuit.png',4,15,12,'recurring','true');
INSERT INTO animations (id,`name`,`description`,`dateStart`,`dateEnd`,pictureUrl,popularity,totalPlaces,remainingPlaces,recurrence,enabled) VALUES (3,'Jeux de société','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc sed ligula pellentesque, imperdiet magna vel, bibendum diam. Nullam quis laoreet leo. Curabitur et ex non massa efficitur venenatis. Vestibulum at mi erat. Ut varius, augue vitae iaculis vehicula, sapien diam tempor mauris, in interdum libero leo ac ex. Fusce mi dui, efficitur in lectus in, tincidunt lobortis lorem. Morbi tincidunt dolor quis auctor imperdiet. Praesent nec odio lacinia, volutpat ex sed, molestie quam. Maecenas porttitor, tortor non aliquam pellentesque, dolor diam maximus neque, vitae sollicitudin orci quam venenatis risus.','2023-05-02 14:00:00','2023-05-02 18:30:00','./assets/pictures/animations/atelier-jeux-de-societe.png',2,25,7,'recurring','true');
INSERT INTO animations (id,`name`,`description`,`dateStart`,`dateEnd`,pictureUrl,popularity,totalPlaces,remainingPlaces,recurrence,enabled) VALUES (4,"Ciné\'Chat",'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc sed ligula pellentesque, imperdiet magna vel, bibendum diam. Nullam quis laoreet leo. Curabitur et ex non massa efficitur venenatis. Vestibulum at mi erat. Ut varius, augue vitae iaculis vehicula, sapien diam tempor mauris, in interdum libero leo ac ex. Fusce mi dui, efficitur in lectus in, tincidunt lobortis lorem. Morbi tincidunt dolor quis auctor imperdiet. Praesent nec odio lacinia, volutpat ex sed, molestie quam. Maecenas porttitor, tortor non aliquam pellentesque, dolor diam maximus neque, vitae sollicitudin orci quam venenatis risus.','2023-05-06 20:00:00','2023-05-07 01:30:00','./assets/pictures/animations/lunette-popcorn.png',3,15,0,'occasional','true');

INSERT INTO productscategory (id, `name`, `description`) VALUES (1,'Café Classique',NULL);
INSERT INTO productscategory (id, `name`, `description`) VALUES (2,'Expresso',NULL);
INSERT INTO productscategory (id, `name`, `description`) VALUES (3,'Café avec du lait',NULL);
INSERT INTO productscategory (id, `name`, `description`) VALUES (4,'Café infusé',NULL);
INSERT INTO productscategory (id, `name`, `description`) VALUES (5,'Autres',NULL);

INSERT INTO products (id,`name`,`description`,pictureUrl,popularity,price,discount,productsCategoryId,enabled) VALUES (1,'café noir','null','./assets/pictures/products/café-noir.png',1,1.20,0,1,'true');
INSERT INTO products (id,`name`,`description`,pictureUrl,popularity,price,discount,productsCategoryId,enabled) VALUES (2,'cappucino','null','./assets/pictures/products/cappucino.png',2,3.25,0,3,'true');
INSERT INTO products (id,`name`,`description`,pictureUrl,popularity,price,discount,productsCategoryId,enabled) VALUES (3,'expresso','null','./assets/pictures/products/expresso.png',3,4.50,0,2,'true');
INSERT INTO products (id,`name`,`description`,pictureUrl,popularity,price,discount,productsCategoryId,enabled) VALUES (4,'red-eye','description','./assets/pictures/products/red-eye.png',4,2.75,0,3,'true');
INSERT INTO products (id,`name`,`description`,pictureUrl,popularity,price,discount,productsCategoryId,enabled) VALUES (4,'doppio','description','./assets/pictures/products/doppio.png',4,2.75,0,3,'true');
INSERT INTO products (id,`name`,`description`,pictureUrl,popularity,price,discount,productsCategoryId,enabled) VALUES (4,'cortado','description','./assets/pictures/products/cortado.png',4,2.75,0,3,'true');
INSERT INTO products (id,`name`,`description`,pictureUrl,popularity,price,discount,productsCategoryId,enabled) VALUES (4,'americano','description','./assets/pictures/products/americano.png',4,2.75,0,3,'true');